M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Wed May 20 07:12:28 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-20T07:12:28+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X5.64Y-53.6
T1
X5.64Y-46.55G85X5.64Y-46.25
G05
M30
